module : EndoSSL.feature_extraction.FeatureExtraction
model : EndoSSL.EndoSSL
data_root : /scratch/syangcw
dataset : cataract_feature_extract.CATARACTFeatureExtract
out_features : 19
input_height : 224
input_width : 224
batch_size : 1000
learning_rate : 0.0005
dataset_mode : img
early_stopping_metric : val_acc_phase
save_top_k : 1
max_epochs : 30 # 30
min_epochs : 20 # 20
num_sanity_val_steps : 4
test_extract : True
#accelerator: ddp_spawn
num_workers : 12
gpus : 0 # all available -1
# Cataract-21 0.0005 30 20
# Cataract-101 0.00001 30 20
# Cholec80 0.00001 30 20
# CATARACT 0.0001 30 20