module : mstcn.tecno.TeCNO
model : mstcn.MultiStageModel
dataset : cataract.CATARACT
out_features : 19
num_workers : 3
batch_size : 1
log_every_n_steps : 1
mstcn_causal_conv : True
learning_rate : 0.0001
min_epochs : 12
max_epochs : 50
mstcn_layers : 8
mstcn_f_maps : 32
mstcn_f_dim: 2048
mstcn_stages : 2
early_stopping_metric : val_acc_video
save_top_k : 1
gpus : ['1']
data_root : /home/syangcw/SurgVISTA/downstream/downstream_TeCNO/logs/250109-014616_FeatureExtraction_CATARACTFeatureExtract_EndoSSL_EndoSSL/cataract_pickle_export
num_sanity_val_steps: 1

