CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch \
--nproc_per_node=2 \
--master_port 12326 \
downstream_triplet/run_triplet_training.py \
--batch_size 16 \
--epochs 50 \
--save_ckpt_freq 10 \
--model  unified_base_st \
--pretrained_data settingD \
--pretrained_method videomae-st \
--lr 5e-4 \
--layer_decay 0.75 \
--warmup_epochs 5 \
--data_path /scratch/mmendoscope/downstream/CholecT50 \
--eval_data_path /scratch/mmendoscope/downstream/CholecT50 \
--nb_classes 100 \
--data_strategy online \
--output_mode key_frame \
--num_frames 32 \
--sampling_rate 2 \
--data_set CholecT50C \
--data_fps 1fps \
--output_dir /project/mmendoscope/downstream_uni/CholecT50/Challenge \
--log_dir /project/mmendoscope/downstream_uni/CholecT50/Challenge \
--num_workers 16 \
--dist_eval \
--enable_deepspeed \
--no_auto_resume